title: Daniel September # your name (or website title) here
logo: "/images/Linkedin Picture.png?raw=true" # your photo (or logo) here
description: Data Professional with 4 years experience in Transportation and Logistics and currently completing Google Data Analytics certificate. Experienced in data analytics, data visualization, report generation, project management with expertise in Excel, Postgresql, SPSS, Tableau, and PowerBI. Seeking a data analytics role with opportunities for growth, management, and collaboration within a dynamic team.
  <br><br>

About me: Amazon Process Assistant with 4 years experience in Transportation and Logistics and currently completing Google Data Analytics certificate. Experienced in data analytics, data visualization, report generation, project management with expertise in Excel, Postgresql, SPSS, Tableau, and PowerBI. Seeking a data analytics role with opportunities for growth, management, and collaboration within a dynamic team.
  <br><br>

  
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/danielmseptember/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
linkedin: 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
