title: Daniel M. September # your name (or website title) here
logo: "/images/Linkedin Picture.png?raw=true" resize_settings: width: 100 height: 100 
logo: "/images/Google DA Badge.png?raw=true"


description: Data Professional with 4 years experience in Transportation and Logistics and recently completed my Google Data Analytics certificate. Experienced in data analytics, data visualization, report generation, project management with expertise in Excel, Postgresql, SPSS, Tableau, and PowerBI.Email: danielmseptember1@gmail.com Linkedin: https://www.linkedin.com/in/danielmseptember 

---

  
  Second description 
  <br><br>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: UA-000000-0 # your Google Analytics tracking ID here

<a href="https://www.linkedin.com/in/danielmseptember/">View My LinkedIn Profile</a> 
